# A Feed Forward Neural Network that Learns to Add Numbers from -10 to 10

In [ ]:
# Load libraries / packages / functions
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

# Change the graphics settings to display vector graphics for prettier outputs
from IPython import display
display.set_matplotlib_formats('svg')

In [1]:
# Load externally defined functions / classes
%run create_data
%run create_model
%run train_model

In [2]:
create_data(10)

(array([ 2,  3, -7, -6,  8,  9,  9, -3, -2, -1]),
 array([-10,  -6,   5,   6,  -6]),
 array([ 1, -7, -7,  5, -4]))