# A Feed Forward Neural Network that Learns to Add Numbers from -10 to 10

In [1]:
# Load libraries / packages / functions
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

# Change the graphics settings to display vector graphics for prettier outputs
from IPython import display
display.set_matplotlib_formats('svg')

/var/folders/wk/cgsrf1m50qx268ccx7b33rdr0000gn/T/ipykernel_30808/762136488.py:11: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  display.set_matplotlib_formats('svg')


In [17]:
# Load externally defined functions / classes
from create_data import create_data
#%run create_model
#%run train_model
%run create_data

In [18]:
train_data, test_data, holdout_data = create_data(10)


array([[ -7,  -8],
       [ -5,  -8],
       [ -5,  -2],
       [  8,   9],
       [  5,  -3],
       [  2,   5],
       [-10,   7],
       [  9,   6],
       [  0,   4],
       [  7,  -5]])

In [56]:
train_data

array([[-15],
       [-13],
       [ -7],
       [ 17],
       [  2],
       [  7],
       [ -3],
       [ 15],
       [  4],
       [  2]])

In [57]:
test_data

array([[ -7,  -8],
       [ -5,  -8],
       [ -5,  -2],
       [  8,   9],
       [  5,  -3],
       [  2,   5],
       [-10,   7],
       [  9,   6],
       [  0,   4],
       [  7,  -5]])

In [ ]:
holdout_data